---
title: "Lab 1"
description: "FPGA and MCU Setup"
author: "Lindsey Sands"
date: "9/8/26"
categories:
  - reflection
  - labreport
draft: false
---
## Introduction

## Design and Testing Methodology

## Technical Documentation

# Block Diagram 

# Schematic

## Results and Discussion

# Testbench Simulation

## Conclusion

## AI Prototype Summary



Specs:
Documentation embedded in a well-structured, concise report with one section per major deliverable. Sections should match structure of other specs.
Spoiler tags are used to hide screenshots and code. Some unspoilered entries (~1 waveform, essential code snippets) allowed if they are essential to the narrative, kept to a minimum.
Writeup contains minimal spelling or grammar issues and any errors do not significantly detract from clarity of the writeup.
Statement of whether the design meets all the requirements. If not, list the shortcomings.
AI prototype attempted and some reflection is recorded.
Number of hours spent working on the lab are included.
(Optional) List comments or suggestions on what was particularly good about the assignment or what you think needs to change in future versions.
